server:
  port: 8787

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/amu?serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: amu
    password: amu

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Mybatis 설정
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mapper/*.xml

#file:
#  upload-dir: /Users/amu/Downloads/upload/
