server:
  port: 8787

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/amu?serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: amu
    password: amu

# Mybatis
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mapper/**/*.xml