server:
  port: 8787
  servlet:
    session:
      timeout: 30m

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/amu?serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: amu
    password: amu

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    resources:
      static-locations: file:///C:/AMU_asset/

mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.myspringweb.amu_back.domain.dto
